name: default docker build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: docker build the scraper
        run: |
          ls -lrth;
          docker build ./src -t ${{ secrets.DOCKER_HUB_USERNAME }}/coinbase-scraper:${{ github.sha }}
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/coinbase-scraper:${{ github.sha }}
      - name: docker run
        run: |
          docker run --detach -p 127.0.0.1:${{ env.APP_PORT }}:${{ env.APP_PORT }}/tcp ${{ secrets.DOCKER_HUB_USERNAME }}/coinbase-scraper:${{ github.sha }}
    env:
        APP_PORT: 5001
  
  test-mock-service:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Test endpoint
        run: |
          docker run --name mock-coinbase-service --detach -p 127.0.0.1:${{ env.APP_PORT }}:${{ env.APP_PORT }}/tcp ${{ secrets.DOCKER_HUB_USERNAME }}/coinbase-scraper:${{ github.sha }};
          curl "127.0.0.1:${{ env.APP_PORT }}/" -o output.json;
          cat output.json| jq .msg.data.currency || (echo fail && exit 1);
      # - name: curl
      #   uses: wei/curl@master
      #   with:
      #     args: "127.0.0.1:${{ env.APP_PORT }}/ -o output.json"
    env:
        APP_PORT: 5001

  helm_deployment:
    runs-on: 'ubuntu-latest'
    needs: docker-build-push
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'coinbase-scraper'
        namespace: 'coinbase'
        chart: 'coinbase-scraper'
        token: '${{ github.token }}'
        value-files: ./helm/coinbase-scraper/values.yaml
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
  